### ISSUE TITLE
What's the server side of this project?

### ISSUE THREAD

**Issue by gaoyingie** [ethand91/mediasoup-android-sample#1]
Hi, ethand91:
I have build this project for my phone, and I also build your mediasoup3-wsdemo , then I found that this android side dose not match the server side(wsdemo). Can you help me figure out the corresponding version of server side? Thanks.

**Comment by pintukumarpatil** [comment]
> Hi, ethand91:
> I have build this project for my phone, and I also build your mediasoup3-wsdemo , then I found that this android side dose not match the server side(wsdemo). Can you help me figure out the corresponding version of server side? Thanks.

Hi, @gaoyingie
You can see https://github.com/pintukumarpatil/mediasoup-demo-android, This one is fork from the same repo, I just made changes in app according to  WS mediasoup3-wsdemo. But i am getting false every time at Router.canConsume at WS.  @ethand91 can you help me to find out the solution of this issue.
Console : user cannot consume producer id e8e5160c-2df3-4126-92b5-841288723632

**Comment by ethand91** [comment]
@gaoyingie @pintukumarpatil 
This will not work with "mediasoup3-wsdemo".
Although it is still incomplete I have uploaded the source at: https://github.com/ethand91/mediasoup-sample-server
Please use the above and let me know if it works. (Be sure to change the IP of the webRtcTransport located in "config.js")
Keep in mind it is still not fully complete
