### ISSUE TITLE
Error in android app, After refreshing web app.

### ISSUE THREAD

**Issue by pintukumarpatil** [ethand91/mediasoup-android-sample#2]
Hello @ethand91, getting error after same room join from android and web, and then refresh website getting blow error at mobile end.
  
D/mediasoupclient-jni: [DEBUG] Handler::Receive() | calling pc->SetLocalDescription() [answer:v=0
    o=- 7012044390518046717 5 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=msid-semantic:  WMS
    a=group:BUNDLE 0 1 2 3
    m=video 35771 UDP/TLS/RTP/SAVPF 101 102
    c=IN IP4 192.168.232.2
    a=rtpmap:101 VP8/90000
    a=rtpmap:102 rtx/90000
    a=fmtp:102 apt=101
    a=rtcp:9 IN IP4 0.0.0.0
    a=rtcp-fb:101 transport-cc
    a=rtcp-fb:101 ccm fir
    a=rtcp-fb:101 nack
    a=rtcp-fb:101 nack pli
    a=extmap:12 urn:ietf:params:rtp-hdrext:toffset
    a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=extmap:11 urn:3gpp:video-orientation
    a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
    a=extmap:6 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
    a=setup:active
    a=mid:0
    a=recvonly
    a=ice-ufrag:j90b
    a=ice-pwd:HWy3Ug7tGwAsd6dItPnV7mn2
    a=fingerprint:sha-256 EE:D8:92:F6:00:C2:BB:6B:4B:6A:3D:FC:90:D9:BD:27:14:96:DB:98:A8:FC:27:0D:60:63:83:97:AA:A0:72:78
    a=candidate:3362660723 1 udp 2122260223 192.168.232.2 35771 typ
2019-11-20 12:33:52.697 23830-23893/com.example.mediasoupandroidsample W/mediasoupclient-jni: [WARN] PeerConnection::OnFailure() | webtc::SetSessionDescriptionObserver failure [INTERNAL_ERROR:Failed to set local answer sdp: Failed to process the bundled m= section.]
2019-11-20 12:33:52.698 23830-23862/com.example.mediasoupandroidsample E/mediasoupclient-jni: [ERROR] transport_jni::Java_org_mediasoup_droid_RecvTransport_nativeConsume() | Failed to set local answer sdp: Failed to process the bundled m= section.

**Comment by ethand91** [comment]
Hello @pintukumarpatil 
Thanks for the report. 
I'll have a look into it however this seems to be an issue with mediasoup-client-android.
Someone else has already reported it: 
https://github.com/haiyangwu/mediasoup-client-android/issues/4

**Comment by ethand91** [comment]
https://mediasoup.discourse.group/t/failed-to-process-the-bundled-m-section/233

**Comment by ethand91** [comment]
Fixed it was a problem with the consume race condition.

Please note you will also need to update the server side as well for it to work:
https://github.com/ethand91/mediasoup-sample-server
