### ISSUE TITLE
still sdp m=section error

### ISSUE THREAD

**Issue by newchenyu** [ethand91/mediasoup-android-sample#4]
Hello @ethand91 
In my case,I got 'm=section error' from this method
![WX20191122-102411@2x.png](https://i.loli.net/2019/11/22/szOxrDaEZqcpuLU.png)
**I have set the server 'paused' to true.but this error still exists.**
could I have some suggest from you?

**Comment by ethand91** [comment]
Hello @newchenyu 
After creating the consumer on the server side could you confirm that the output of (consumer.paused) is true.

Also if you could give the steps you took to get this error I could try to reproduce it.

You could also enable mediasoup debug logs and check for any issues there.

**Comment by newchenyu** [comment]
@ethand91 
My mistake.The server is not update.Set paused to true is used.
Thanks a lot.
